### ISSUE TITLE
Static initialization of control block

### ISSUE THREAD

**Issue by katyo** [wez/jlink_rtt#2]
As I see, you check RTT control block on each I/O operation.
May be I didn't understand quite well in details but I think we can simply initialize it statically similar to the reference implementation in C from Segger.

**Comment by katyo** [comment]
Of course, it still require some init for code-in-ram case, but it's not so often use case in embedded development.

**Comment by wez** [comment]
Resolved in 1907b7f7025d4ad79e7164da46fc6f3f6a218cce
